'use strict'
const test = require('tape')

const { DescBelongsTo, DescHasMany } = require('./descriptors')

test('DescBelongsTo: all fields are provided', (t) => {
  const belongsToDescription = new DescBelongsTo('group', {
    belongsTo: 'userGroup',
    fkField: 'GrpID',
    fkAs: 'customNamedId'
  })

  t.equal(belongsToDescription.modelFieldName, 'group')
  t.equal(belongsToDescription.relationModelName, 'userGroup')
  t.equal(belongsToDescription.fkField, 'GrpID')
  t.equal(belongsToDescription.fkAs, 'customNamedId')

  t.end()
})

test('DescBelongsTo: partially provided fields', (t) => {
  t.equal(
    new DescBelongsTo('group', {
      belongsTo: 'userGroup',
      fkField: 'GrpID'
    }).fkAs,
    'userGroupId',
    'autogenerated fkAs is camel cased foreign model name + Id'
  )

  t.equal(
    new DescBelongsTo('group', {
      belongsTo: 'user-group'
    }).fkField,
    'userGroup',
    'autogenerated fkField is camel cased foreign model name'
  )

  t.end()
})

test('DescBelongsTo: throws if no crucial field provided', (t) => {
  t.throws(
    () => new DescBelongsTo('group', {}),
    /belongsTo field is undefined/,
    'belongsTo field is crucial for belongsTo descriptor'
  )

  t.throws(
    () => new DescBelongsTo('group'),
    /descriptorObject attribute is undefined/
  )

  t.throws(
    () => new DescBelongsTo(void 0, {}),
    /modelNameField attribute is undefined/
  )

  t.end()
})

/**
 * DescHasMany
 */
test('DescHasMany: all fields are provided', (t) => {
  const hasManyDescription = new DescHasMany('userAccounts', {
    hasMany: 'userAccount',
    fkField: 'GrpID'
  })

  t.equal(hasManyDescription.modelFieldName, 'userAccounts')
  t.equal(hasManyDescription.relationModelName, 'userAccount')
  t.equal(hasManyDescription.fkField, 'GrpID')

  t.end()
})

test('DescHasMany: throws if no crucial field provided', (t) => {
  t.throws(
    () => new DescHasMany('users', {
      hasMany: 'user'
    }),
    /fkField field is undefined/,
    'fkField field is crucial for hasMany descriptor'
  )

  t.throws(
    () => new DescHasMany('users', {}),
    /hasMany field is undefined/,
    'hasMany field is crucial for hasMany descriptor'
  )

  t.throws(
    () => new DescHasMany('users'),
    /descriptorObject attribute is undefined/
  )

  t.throws(
    () => new DescHasMany(void 0, {}),
    /modelNameField attribute is undefined/
  )

  t.end()
})
